version: '3'

services:
  nginx:
    image: nginx:1.28
    container_name: nginx
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/var/www
      - ./certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped